#pragma once
struct ID3D11Device;
struct ID3D11Buffer;
struct ID3D11DeviceContext;
struct IDXGISwapChain;
struct ID3D11RenderTargetView;
struct ID3D11ShaderResourceView;
struct ID3D11Texture2D;
struct ID3D11BlendState;
struct ID3D11DepthStencilView;
struct ID3D11DepthStencilState;
struct IDXGIAdapter;
struct D3D11_INPUT_ELEMENT_DESC;
struct ID3D11VertexShader;
struct ID3D11PixelShader;
struct ID3D11ShaderReflection;
struct ID3D11InputLayout;
struct ID3D11RasterizerState;
